supporter/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'supporter'
urlpatterns = [
    path('', views.Login.as_view(), name = 'Login'),
    path('Login/LoginProf', views.LoginProf.as_view(), name = 'LoginProf'),
    path('Login/LoginStud', views.LoginStud.as_view(), name = 'LoginStud'),
    path('Login/LoginAdmin', views.LoginAdmin.as_view(), name = 'LoginAdmin'),
    path('Login/Check/', views.Check, name = 'Check'),
    path('Login/Check2/', views.Check2, name = 'Check2'),
    path('Login/Check3/', views.Check3, name = 'Check3'),
    path('Login/ProfMemb/', views.ProfMemb.as_view(), name = 'ProfMemb'),
    path('Login/StudMemb/', views.StudMemb.as_view(), name = 'StudMemb'),
    path('Prof/<int:professor_id>/', views.ProfUser.as_view(), name='ProfUser'),
    path('Prof/<int:professor_id>/Info/', views.ProfUserinfo.as_view(), name='ProfInfo'),
    path('Prof/<int:professor_id>/AddLec/', views.AddLecP.as_view(), name='AddLecP'),
    path('Prof/<int:professor_id>/<int:lecture_id>/', views.LecInfo.as_view(), name='LecInfo'),
    path('Prof/<int:professor_id>/<int:lecture_id>/Change/', views.ProflectureChange.as_view(), name='LecChange'),
    path('Prof/<int:professor_id>/<int:lecture_id>/lecdele/', views.dele, name = 'lecdeld'),
    path('Prof/<int:professor_id>/<int:lecture_id>/AttendBook/', views.AttendBook.as_view(), name='AttendBook'),
    path('Prof/<int:professor_id>/<int:lecture_id>/AddBoard/', views.AddBoard.as_view(), name='AddBoard'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/', views.BoardList.as_view(), name='BoardList'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/', views.BoardInfo.as_view(), name='BoardInfo'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/Change/', views.ProfBoardChange.as_view(), name='BoardChange'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/BoardDel/', views.BoardDel, name = 'BoardDel'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/AddReply/', views.AddReply, name='AddReply'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/<int:reply_id>/ReplyDel/', views.ReplyDel, name='ReplyDel'),
    path('Prof/<int:professor_id>/<int:lecture_id>/AddReport/', views.AddReport.as_view(), name='AddReport'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/', views.ReportList.as_view(), name='ReportList'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/', views.ReportInfo.as_view(), name='ReportInfo'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/Change/', views.ProfReportChange.as_view(), name='ReportChange'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/ReportDel/', views.ReportDel, name = 'ReportDel'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/AddReply/', views.AddRepoReply, name='AddRepoReply'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/<int:reply_id>/ReplyDel/', views.RepoReplyDel, name='RepoReplyDel'),
    path('Stud/<int:student_id>/', views.StudUser.as_view(), name='StudUser'),
    path('Stud/<int:student_id>/Info/', views.StudUserinfo.as_view(), name='StudInfo'),
    path('Stud/<int:student_id>/application/', views.LecList.as_view(), name = 'leclist'),
    path('Stud/<int:student_id>/application/<int:lecture_id>/', views.StudApplication.as_view(), name = 'application'),
    path('Stud/<int:student_id>/application/<int:lecture_id>/Check/', views.LecCheck.as_view(), name = 'lecCheck'),
    path('Stud/<int:student_id>/<int:lecture_id>/', views.StudLecInfo.as_view(), name='StudLecInfo'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/', views.BoardListStud.as_view(), name='BoardListStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/<int:board_id>/', views.BoardInfoStud.as_view(), name='BoardInfoStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/<int:board_id>/AddReply/', views.AddReplyStud, name='AddReplyStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/<int:board_id>/<int:reply_id>/ReplyDel/', views.ReplyStudDel, name='ReplyStudDel'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/', views.ReportListStud.as_view(), name='ReportListStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/', views.ReportInfoStud.as_view(), name='ReportInfoStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/AddReply/', views.AddRepoReplyStud, name='AddRepoReplyStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/ReportManagStud/', views.ReportManagStud.as_view(), name='ReportManagStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/ReportDel/', views.Report_StudDel, name='Report_StudDel'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/<int:reply_id>/ReplyDel/', views.RepoReplyStudDel, name='RepoReplyStudDel'),
    ] 

teamProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Main/', include('supporter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supporter/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.urls import reverse
from django.db import connection
from .forms import *
from .models import *
# Create your views here.

class Login(View):
    template_name = 'supporter/Login.html'

    def get(self, request, *args, **kwargs):
        request.session['LoginProf'] = False #여기 변경
        try:
            admin = Professor.objects.get(pk = 1)
            print("관리자 있음")
        except:
            print("관리자 없음 새로만들기 시작")
            new_admin = Professor(prof_id = "admin@admin.admin", prof_num = 0000, prof_name = "관리자", prof_password = "admin", prof_Phone = "000")
            new_admin.save()

        return render(request, self.template_name)

class LoginProf(View):
    form_class = LoginForm
    template_name = 'supporter/LoginProf.html'

    def get(self, request, *args, **kwargs):
        request.session['LoginProf'] = False #여기 변경
        form = LoginForm(request.GET)

        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwargs):
        memb_form = Membership(request.POST)
        form = LoginForm(request.GET)
        if memb_form.is_valid():
            new_id = memb_form.cleaned_data['id_text']
            new_pw = memb_form.cleaned_data['pw_text']
            new_num = memb_form.cleaned_data['number_text']
            new_name = memb_form.cleaned_data['name_text']
            new_phone = memb_form.cleaned_data['phone_text']

            new_user = Professor(prof_id = new_id, prof_password = new_pw, prof_num = new_num, prof_name = new_name, prof_Phone = new_phone)
            new_user.save()

        return render(request, self.template_name, {'form':form})

class LoginStud(View):
    form_class = LoginForm
    template_name = 'supporter/LoginStud.html'

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.GET)
        request.session['LoginStud'] = False #여기 변경

        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwargs):
        form = Membership(request.POST)
        retForm = LoginForm(request.GET)
        if form.is_valid():
            new_id = form.cleaned_data['id_text']
            new_pw = form.cleaned_data['pw_text']
            new_num = form.cleaned_data['number_text']
            new_name = form.cleaned_data['name_text']
            new_phone = form.cleaned_data['phone_text']

            new_user = Student(stud_id = new_id, stud_password = new_pw, stud_num = new_num, stud_name = new_name, stud_Phone = new_phone)
            new_user.save()

        return render(request, self.template_name, {'form':retForm})

def Check(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['id_text']
            user_pw = form.cleaned_data['pw_text']
            try:
                user = Professor.objects.get(prof_id = user_id, prof_password = user_pw)
            except Professor.DoesNotExist:
                raise Http404("Professor does not exist!!!!")
            request.session['LoginProf'] = True #여기 변경
            request.session.set_expiry(600) # 여기 변경
            return HttpResponseRedirect(reverse('supporter:ProfUser', args=(user.id,)))
    
def Check2(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['id_text']
            user_pw = form.cleaned_data['pw_text']
            try:
                user = Student.objects.get(stud_id = user_id, stud_password = user_pw)
            except Student.DoesNotExist:
                raise Http404("Student does not exist!!!!")
            request.session['LoginStud'] = True #여기 변경
            request.session.set_expiry(600) # 여기 변경

            return HttpResponseRedirect(reverse('supporter:StudUser', args=(user.id,)))

def Check3(request):
    if request.method == 'POST':
        form = AdminForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['id_text']
            user_pw = form.cleaned_data['pw_text']
            if user_id == user_pw and user_pw == "admin":
                request.session['LoginProf'] = True #여기 변경
                request.session.set_expiry(600) # 여기 변경
                try:
                    user = Professor.objects.get(pk = 1, prof_password = user_pw)
                except Professor.DoesNotExist:
                    raise Http404("Professor does not exist!!!!")
                
            else:
                raise Http404("Admin Login Fail!!!")


            return HttpResponseRedirect(reverse('supporter:ProfUser', args=(user.id,)))
    
class LoginAdmin(View):
    form_class = AdminForm
    template_name = 'supporter/LoginAdmin.html'

    def get(self, request, *args, **kwargs):
        request.session['LoginProf'] = False #여기 변경
        form = AdminForm(request.GET)

        return render(request, self.template_name, {'form':form})


class StudUser(View):
    template_name = 'supporter/StudUserMain.html'
    
    def get(self, request, *args, **kwargs):
        user_id = kwargs['student_id']
        user = Student.objects.get(id = user_id)

        addList = Attend.objects.all().filter(att_stud = user_id)

        return render(request, self.template_name, {'user':user, 'addList':addList})


class ProfUser(View):
    template_name = 'supporter/ProfUserMain.html'
    
    def get(self, request, *args, **kwargs):
        
        user_id = kwargs['professor_id']
        user = Professor.objects.get(id = user_id)
        if user_id != 1:
            lectList = Lecture.objects.all().filter(lec_prof = user_id)
        else:
            lectList = Lecture.objects.all()

        return render(request, self.template_name, {'user':user, 'lectList' : lectList})

    def post(self, request, *args, **kwargs):
        user_id = kwargs['professor_id']
        user = Professor.objects.get(pk = user_id)
        form = LectureForm(request.POST)        
        if form.is_valid():
            new_lecName = form.cleaned_data['lec_name']
            new_lecYear = form.cleaned_data['lec_year']
            new_lecSeme = form.cleaned_data['lec_seme']
            new_lecInfo = form.cleaned_data['lec_info']
            new_lecProf = form.cleaned_data['Professor_id']
            new_lecture = Lecture(lec_name = new_lecName, lec_year = new_lecYear, lec_seme = new_lecSeme, lec_info = new_lecInfo, lec_prof = Professor.objects.get(pk = user_id))
            new_lecture.save()
            lectList = Lecture.objects.all().filter(lec_prof = user_id)
            return render(request, self.template_name, {'user':user, 'lectList':lectList})

class ProfUserinfo(View):
    template_name = 'supporter/BeforeProfInfo.html'
    
    def get(self, request, *args, **kwargs):
        if not request.session.get('LoginProf', False): # 여기 변경
            return render(request, 'supporter/Login.html') # 여기 변경
        else:
            user_id = kwargs['professor_id']
            user = Professor.objects.get(id = user_id)
            form = Join(initial={'number_text':user.prof_num, 'name_text':user.prof_name, 'phone_text':user.prof_Phone})

            return render(request, self.template_name, {'user': user ,'form': form})
    
    def post(self, request, *args, **kwargs):
        form = Join(request.POST)
        if form.is_valid():
            user_pw = form.cleaned_data['pw_text']
            user_num = form.cleaned_data['number_text']
            user_name = form.cleaned_data['name_text']
            user_phone = form.cleaned_data['phone_text']

            user_id = kwargs['professor_id']
            user = Professor.objects.get(id = user_id)
            user.prof_password = str(user_pw)
            user.prof_num = str(user_num)
            user.prof_name = str(user_name)
            user.prof_Phone = str(user_phone)
            user.save()
            
            return render(request, 'supporter/AfterProfInfo.html', {'form' : form})

class StudUserinfo(View):
    template_name = 'supporter/BeforeStudInfo.html'

    def get(self, request, *args, **kwargs):
        if not request.session.get('LoginStud', False): # 여기 변경
            return render(request, 'supporter/Login.html') # 여기 변경
        else:
            user_id = kwargs['student_id']
            user = Student.objects.get(id = user_id)
            form = Join(initial={'number_text':user.stud_num, 'name_text':user.stud_name, 'phone_text':user.stud_Phone})

        return render(request, self.template_name, {'user': user ,'form': form})

    def post(self, request, *args, **kwargs):
        form = Join(request.POST)
        if form.is_valid():
            user_pw = form.cleaned_data['pw_text']
            user_num = form.cleaned_data['number_text']
            user_name = form.cleaned_data['name_text']
            user_phone = form.cleaned_data['phone_text']

            user_id = kwargs['student_id']
            user = Student.objects.get(id = user_id)
            user.stud_password = str(user_pw)
            user.stud_num = str(user_num)
            user.stud_name = str(user_name)
            user.stud_Phone = str(user_phone)
            user.save()
            
            return render(request, 'supporter/AfterStudInfo.html', {'form' : form})

class LecList(View):
    template_name = 'supporter/Lecturelist.html'

    def get(self, request, *args, **kwargs):
        user_id = kwargs['student_id']
        lectList = Lecture.objects.all()

        return render(request, self.template_name, {'lectList' : lectList, 'user_id':user_id})

    def post(self, request, *args, **kwargs):
        user_id = kwargs['student_id']
        lectList = Lecture.objects.all()

supporter/templates/supporter/AfterStudInfo.html
<h1>개인정보수정완료</h1>

<a href = "{% url 'supporter:LoginStud' %}">로그인창으로 돌아가기!!</a><br>

supporter/templates/supporter/AttendBook.html
<h1>출석부</h1>
<h3>교수님 : {{user.prof_name}}</h3>
<h3>과목 : {{lect.lec_name}}</h3>
<table border = "1">
    <tbody>
        <tr><td>학번</td><td>이름</td><td>전화번호</td><td>1주차</td><td>2주차</td><td>3주차</td><td>4주차</td><td>5주차</td>
            <td>6주차</td><td>7주차</td><td>8주차</td><td>9주차</td><td>10주차</td>
            <td>11주차</td><td>12주차</td><td>13주차</td><td>14주차</td><td>15주차</td></tr><br>
        {% for student in attendList %}
        <tr><td>{{student.att_stud.stud_num}}</td><td>{{student.att_stud.stud_name}}</td><td>{{student.att_stud.stud_Phone}}</td><td></td><td></td><td></td><td></td><td></td>
            <td></td><td></td><td></td><td></td><td></td>
            <td></td><td></td><td></td><td></td><td></td></tr><br>
        {% endfor %}
    </tbody>
</table>
<br>
<a href = "{% url 'supporter:LecInfo' user.pk lect.pk %}" method = 'get'>돌아가기</a>

supporter/templates/supporter/BeforeStudInfo.html
<h1>개인정보수정</h1>
<form action = "{% url 'supporter:StudInfo' user.pk %}" method = 'post'>
    {% csrf_token %}
    아이디 : {{ user.stud_id }}<br>

    {% for fo in form %}
        {% if fo.label %}
            <br>{{fo.label|safe}}
        {% endif %}
        {{ fo }}
    {{ fo.help_text|safe }}
{% endfor %}

<br><input type='submit' value='변경완료' />
</form>

supporter/templates/supporter/ChangeLecture.html
<h1>강의수정</h1>
<form action = "{% url 'supporter:LecInfo' user.pk lect.pk %}" method = 'post'>
    {% csrf_token %}
    강의교수 : {{ lect.lec_prof }}<br>

    {% for fo in form %}
        {% if fo.label %}
            <br>{{fo.label|safe}}
        {% endif %}
        {{ fo }}
    {{ fo.help_text|safe }}
{% endfor %}

<br><input type='submit' value='변경완료' />
</form>

supporter/templates/supporter/Lecturelist.html
<h1>개설 강의 목록</h1>

{% for fo in lectList %}
    <a href = "{% url 'supporter:application' user_id fo.pk %}">{{fo.lec_name}}</a><br>
{% endfor %}

supporter/templates/supporter/Login.html
<h1>강의 지원 사이트</h1>
<br>
<hr>
<a href = "{% url 'supporter:LoginProf' %}">교수용 사용자</a><br>
<a href = "{% url 'supporter:LoginStud' %}">학생용 사용자</a><br>
<a href = "{% url 'supporter:LoginAdmin' %}">관리자용</a><br>

supporter/templates/supporter/ProfAddBoard.html
<h1>게시글 추가</h1>
<form action = "{% url 'supporter:BoardList' user_id lect_id %}" enctype="multipart/form-data"  method = 'post' novalidate>
    {% csrf_token %}
    {% for fo in form %}
        {% if fo.label %}
            <br>{{fo.label|safe}}
        {% endif %}
        {{ fo }}
        {{ fo.help_text|safe }}
    {% endfor %}
    <br><br><input type='submit' value='게시 완료' />
</form>
<form action = "{% url 'supporter:LecInfo' user_id lect_id %}" method = 'get'>
    {% csrf_token %}
<input type='submit' value='취소' />
</form>

supporter/templates/supporter/ProfBoardList.html
{% extends "supporter/Lecture.html" %}

{% block content %}
    <form action = "{% url 'supporter:AddBoard' user.pk lect.pk %}" method = 'get'>
    {% csrf_token %}
    {% for boa in boardList %}
        <li><a href = "{% url 'supporter:BoardInfo' user.pk lect.pk boa.pk %}" method = 'get'>{{boa.board_tittle}}</a></li>    
    {% endfor %}    
    <input type='submit' value='게시글 생성'/><br>
    </form>
    <a href = "{% url 'supporter:LecInfo' user.pk lect.pk %}" method = 'get'>돌아가기</a>
{% endblock%}

supporter/templates/supporter/ProfMemb.html
<h1>교수용 회원가입</h1><hr>

<form action = "{% url 'supporter:LoginProf' %}" method = 'post'>
    {% csrf_token %}
    {% for fo in form %}
        {% if fo.label %}
            <br>{{fo.label|safe}}
        {% endif %}
        {{ fo }}
        {{ fo.help_text|safe }}
    {% endfor %}
    <br>
    <br>
    <input type='submit' value='회원가입' />
</form>

supporter/templates/supporter/ProfReportList.html
{% extends "supporter/Lecture.html" %}

{% block content %}
    <form action = "{% url 'supporter:AddReport' user.pk lect.pk %}" method = 'get'>
    {% csrf_token %}
    {% for repo in reportList %}
        <li><a href = "{% url 'supporter:ReportInfo' user.pk lect.pk repo.pk %}" method = 'get'>{{repo.report_tittle}}</a></li>    
    {% endfor %}    
    <input type='submit' value='새 과제 생성'/><br>
    </form>
    <a href = "{% url 'supporter:LecInfo' user.pk lect.pk %}" method = 'get'>돌아가기</a>
{% endblock%}

supporter/templates/supporter/ProfUserMain.html
{% if user.pk != 1%}
    <h1>{{user.prof_name}}교수님! 안녕하세요</h1>
    <h4>아이디 : {{user.prof_id}}</h4>
    <h4>교수번호 : {{user.prof_num}}</h4>
    <h4>전화번호 : {{user.prof_Phone}}</h4>

<form action = "{% url 'supporter:ProfInfo' user.pk %}" method = 'get'>
    {% csrf_token %}
    <input type='submit' value='개인정보수정' /> 
    <a href = "{% url 'supporter:LoginProf' %}">로그아웃</a>
</form>
{% else %}
    <h1>{{user.prof_name}}님! 안녕하세요</h1>
    <h2>지금 보시는 페이지는 관리자 전용 페이지입니다.</h2>
    <a href = "{% url 'supporter:Login' %}">로그아웃</a>
{% endif %}

<hr><hr>
<h2>현재 강의중인 강의 목록</h2>
<hr>
<form action = "{% url 'supporter:AddLecP' user.pk %}" method = 'post'>
    {% csrf_token %}
    {% for lec in lectList %}
        <li><a href = "{% url 'supporter:LecInfo' user.pk lec.pk %}" method = 'get'>{{lec.lec_name}}</a></li>
    {% endfor %}    
<input type='submit' value='새로운 강의 개설' />
</form>

supporter/templates/supporter/ReportManagementStud.html
<form action = "{% url 'supporter:ReportManagStud' user.pk lect.pk report.pk %}" enctype="multipart/form-data" method = 'post'>
    {% csrf_token %}
    <h1>리포트 작성</h1>
    {% for fo in form%}
    {% if fo.label %}
        <br>{{fo.label|safe}}
    {% endif %}
    {{ fo }}
    {{ fo.help_text|safe }}
    {% endfor %}
    <br><br><input type='submit' value='작성 완료'/><br>
</form> 

supporter/templates/supporter/StudBoardList.html
{% extends "supporter/LectureStud.html" %}

{% block content %}
    {% for boa in boardList %}
        <li><a href = "{% url 'supporter:BoardInfoStud' user.pk lect.pk boa.pk %}" method = 'get'>{{boa.board_tittle}}</a></li>    
    {% endfor %}    
    <a href = "{% url 'supporter:StudLecInfo' user.pk lect.pk %}" method = 'get'>돌아가기</a>
{% endblock%}

supporter/templates/supporter/StudReportList.html
{% extends "supporter/LectureStud.html" %}

{% block content %}
    {% for repo in reportList %}
        <li><a href = "{% url 'supporter:ReportInfoStud' user.pk lect.pk repo.pk %}" method = 'get'>{{repo.report_tittle}}</a></li>    
    {% endfor %}    
    <a href = "{% url 'supporter:StudLecInfo' user.pk lect.pk %}" method = 'get'>돌아가기</a>
{% endblock%}